kind: Service
apiVersion: v1
metadata:
  name: {{ $.Values.mysql.name }}-mysql
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.mysql.name }}-mysql
spec:
  selector:
    app: {{ $.Values.mysql.name }}-mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort