# encoding: utf-8
import os
import time
import pymysql
import re

KEY_WORDS = {"accessible",
"account",
"action",
"active",
"add",
"admin",
"after",
"against",
"aggregate",
"algorithm",
"all",
"alter",
"always",
"analyse",
"analyze",
"and",
"any",
"array",
"as",
"asc",
"ascii",
"asensitive",
"at",
"attribute",
"authentication",
"autoextend_size",
"auto_increment",
"avg",
"avg_row_length",
"backup",
"before",
"begin",
"between",
"bigint",
"binary",
"binlog",
"bit",
"blob",
"block",
"bool",
"boolean",
"both",
"btree",
"buckets",
"bulk",
"by",
"byte",
"cache",
"call",
"cascade",
"cascaded",
"case",
"catalog_name",
"chain",
"challenge_response",
"change",
"changed",
"channel",
"char",
"character",
"charset",
"check",
"checksum",
"cipher",
"class_origin",
"client",
"clone",
"close",
"coalesce",
"code",
"collate",
"collation",
"column",
"columns",
"column_format",
"column_name",
"comment",
"commit",
"committed",
"compact",
"completion",
"component",
"compressed",
"compression",
"concurrent",
"condition",
"connection",
"consistent",
"constraint",
"constraint_catalog",
"constraint_name",
"constraint_schema",
"contains",
"context",
"continue",
"convert",
"cpu",
"create",
"cross",
"cube",
"cume_dist",
"current",
"current_date",
"current_time",
"current_timestamp",
"current_user",
"cursor",
"cursor_name",
"data",
"database",
"databases",
"datafile",
"date",
"datetime",
"day",
"day_hour",
"day_microsecond",
"day_minute",
"day_second",
"deallocate",
"dec",
"decimal",
"declare",
"default",
"default_auth",
"definer",
"definition",
"delayed",
"delay_key_write",
"delete",
"dense_rank",
"desc",
"describe",
"description",
"des_key_file",
"deterministic",
"diagnostics",
"directory",
"disable",
"discard",
"disk",
"distinct",
"distinctrow",
"div",
"do",
"double",
"drop",
"dual",
"dumpfile",
"duplicate",
"dynamic",
"each",
"else",
"elseif",
"empty",
"enable",
"enclosed",
"encryption",
"end",
"ends",
"enforced",
"engine",
"engines",
"engine_attribute",
"enum",
"error",
"errors",
"escape",
"escaped",
"event",
"events",
"every",
"except",
"exchange",
"exclude",
"execute",
"exists",
"exit",
"expansion",
"expire",
"explain",
"export",
"extended",
"extent_size",
"factor",
"failed_login_attempts",
"false",
"fast",
"faults",
"fetch",
"fields",
"file",
"file_block_size",
"filter",
"finish",
"first",
"first_value",
"fixed",
"float",
"float4",
"float8",
"flush",
"following",
"follows",
"for",
"force",
"foreign",
"format",
"found",
"from",
"full",
"fulltext",
"function",
"general",
"generate",
"generated",
"geomcollection",
"geometry",
"geometrycollection",
"get",
"get_format",
"get_master_public_key",
"get_source_public_key",
"global",
"grant",
"grants",
"group",
"grouping",
"groups",
"group_replication",
"gtid_only",
"handler",
"hash",
"having",
"help",
"high_priority",
"histogram",
"history",
"host",
"hosts",
"hour",
"hour_microsecond",
"hour_minute",
"hour_second",
"identified",
"if",
"ignore",
"ignore_server_ids",
"import",
"in",
"inactive",
"index",
"indexes",
"infile",
"initial",
"initial_size",
"initiate",
"inner",
"inout",
"insensitive",
"insert",
"insert_method",
"install",
"instance",
"int",
"int1",
"int2",
"int3",
"int4",
"int8",
"integer",
"intersect",
"interval",
"into",
"invisible",
"invoker",
"io",
"io_after_gtids",
"io_before_gtids",
"io_thread",
"ipc",
"is",
"isolation",
"issuer",
"iterate",
"join",
"json",
"json_table",
"json_value",
"key",
"keyring",
"keys",
"key_block_size",
"kill",
"lag",
"language",
"last",
"last_value",
"lateral",
"lead",
"leading",
"leave",
"leaves",
"left",
"less",
"level",
"like",
"limit",
"linear",
"lines",
"linestring",
"list",
"load",
"local",
"localtime",
"localtimestamp",
"lock",
"locked",
"locks",
"logfile",
"logs",
"long",
"longblob",
"longtext",
"loop",
"low_priority",
"master",
"master_auto_position",
"master_bind",
"master_compression_algorithms",
"master_connect_retry",
"master_delay",
"master_heartbeat_period",
"master_host",
"master_log_file",
"master_log_pos",
"master_password",
"master_port",
"master_public_key_path",
"master_retry_count",
"master_server_id",
"master_ssl",
"master_ssl_ca",
"master_ssl_capath",
"master_ssl_cert",
"master_ssl_cipher",
"master_ssl_crl",
"master_ssl_crlpath",
"master_ssl_key",
"master_ssl_verify_server_cert",
"master_tls_ciphersuites",
"master_tls_version",
"master_user",
"master_zstd_compression_level",
"match",
"maxvalue",
"max_connections_per_hour",
"max_queries_per_hour",
"max_rows",
"max_size",
"max_updates_per_hour",
"max_user_connections",
"medium",
"mediumblob",
"mediumint",
"mediumtext",
"member",
"memory",
"merge",
"message_text",
"microsecond",
"middleint",
"migrate",
"minute",
"minute_microsecond",
"minute_second",
"min_rows",
"mod",
"mode",
"modifies",
"modify",
"month",
"multilinestring",
"multipoint",
"multipolygon",
"mutex",
"mysql_errno",
"name",
"names",
"national",
"natural",
"nchar",
"ndb",
"ndbcluster",
"nested",
"network_namespace",
"never",
"new",
"next",
"no",
"nodegroup",
"none",
"not",
"nowait",
"no_wait",
"no_write_to_binlog",
"nth_value",
"ntile",
"null",
"nulls",
"number",
"numeric",
"nvarchar",
"of",
"off",
"offset",
"oj",
"old",
"on",
"one",
"only",
"open",
"optimize",
"optimizer_costs",
"option",
"optional",
"optionally",
"options",
"or",
"order",
"ordinality",
"organization",
"others",
"out",
"outer",
"outfile",
"over",
"owner",
"pack_keys",
"page",
"parser",
"partial",
"partition",
"partitioning",
"partitions",
"password",
"password_lock_time",
"path",
"percent_rank",
"persist",
"persist_only",
"phase",
"plugin",
"plugins",
"plugin_dir",
"point",
"polygon",
"port",
"precedes",
"preceding",
"precision",
"prepare",
"preserve",
"prev",
"primary",
"privileges",
"privilege_checks_user",
"procedure",
"process",
"processlist",
"profile",
"profiles",
"proxy",
"purge",
"quarter",
"query",
"quick",
"random",
"range",
"rank",
"read",
"reads",
"read_only",
"read_write",
"real",
"rebuild",
"recover",
"recursive",
"redofile",
"redo_buffer_size",
"redundant",
"reference",
"references",
"regexp",
"registration",
"relay",
"relaylog",
"relay_log_file",
"relay_log_pos",
"relay_thread",
"release",
"reload",
"remote",
"remove",
"rename",
"reorganize",
"repair",
"repeat",
"repeatable",
"replace",
"replica",
"replicas",
"replicate_do_db",
"replicate_do_table",
"replicate_ignore_db",
"replicate_ignore_table",
"replicate_rewrite_db",
"replicate_wild_do_table",
"replicate_wild_ignore_table",
"replication",
"require",
"require_row_format",
"reset",
"resignal",
"resource",
"respect",
"restart",
"restore",
"restrict",
"resume",
"retain",
"return",
"returned_sqlstate",
"returning",
"returns",
"reuse",
"reverse",
"revoke",
"right",
"rlike",
"role",
"rollback",
"rollup",
"rotate",
"routine",
"row",
"rows",
"row_count",
"row_format",
"row_number",
"rtree",
"savepoint",
"schedule",
"schema",
"schemas",
"schema_name",
"second",
"secondary",
"secondary_engine",
"secondary_engine_attribute",
"secondary_load",
"secondary_unload",
"second_microsecond",
"security",
"select",
"sensitive",
"separator",
"serial",
"serializable",
"server",
"session",
"set",
"share",
"show",
"shutdown",
"signal",
"signed",
"simple",
"skip",
"slave",
"slow",
"smallint",
"snapshot",
"socket",
"some",
"soname",
"sounds",
"source",
"source_auto_position",
"source_bind",
"source_compression_algorithms",
"source_connect_retry",
"source_delay",
"source_heartbeat_period",
"source_host",
"source_log_file",
"source_log_pos",
"source_password",
"source_port",
"source_public_key_path",
"source_retry_count",
"source_ssl",
"source_ssl_ca",
"source_ssl_capath",
"source_ssl_cert",
"source_ssl_cipher",
"source_ssl_crl",
"source_ssl_crlpath",
"source_ssl_key",
"source_ssl_verify_server_cert",
"source_tls_ciphersuites",
"source_tls_version",
"source_user",
"source_zstd_compression_level",
"spatial",
"specific",
"sql",
"sqlexception",
"sqlstate",
"sqlwarning",
"sql_after_gtids",
"sql_after_mts_gaps",
"sql_before_gtids",
"sql_big_result",
"sql_buffer_result",
"sql_cache",
"sql_calc_found_rows",
"sql_no_cache",
"sql_small_result",
"sql_thread",
"sql_tsi_day",
"sql_tsi_hour",
"sql_tsi_minute",
"sql_tsi_month",
"sql_tsi_quarter",
"sql_tsi_second",
"sql_tsi_week",
"sql_tsi_year",
"srid",
"ssl",
"stacked",
"start",
"starting",
"starts",
"stats_auto_recalc",
"stats_persistent",
"stats_sample_pages",
"status",
"stop",
"storage",
"stored",
"straight_join",
"stream",
"string",
"subclass_origin",
"subject",
"subpartition",
"subpartitions",
"super",
"suspend",
"swaps",
"switches",
"system",
"table",
"tables",
"tablespace",
"table_checksum",
"table_name",
"temporary",
"temptable",
"terminated",
"text",
"than",
"then",
"thread_priority",
"ties",
"time",
"timestamp",
"timestampadd",
"timestampdiff",
"tinyblob",
"tinyint",
"tinytext",
"tls",
"to",
"trailing",
"transaction",
"trigger",
"triggers",
"true",
"truncate",
"type",
"types",
"unbounded",
"uncommitted",
"undefined",
"undo",
"undofile",
"undo_buffer_size",
"unicode",
"uninstall",
"union",
"unique",
"unknown",
"unlock",
"unregister",
"unsigned",
"until",
"update",
"upgrade",
"url",
"usage",
"use",
"user",
"user_resources",
"use_frm",
"using",
"utc_date",
"utc_time",
"utc_timestamp",
"validation",
"value",
"values",
"varbinary",
"varchar",
"varcharacter",
"variables",
"varying",
"vcpu",
"view",
"virtual",
"visible",
"wait",
"warnings",
"week",
"weight_string",
"when",
"where",
"while",
"window",
"with",
"without",
"work",
"wrapper",
"write",
"x509",
"xa",
"xid",
"xml",
"xor",
"year",
"year_month",
"zerofill",
"zone",
"mysql",
"the",
"active",
"admin",
"array",
"attribute",
"authentication",
"buckets",
"bulk",
"challenge_response",
"clone",
"component",
"cume_dist",
"definition",
"dense_rank",
"description",
"empty",
"enforced",
"engine_attribute",
"except",
"exclude",
"factor",
"failed_login_attempts",
"finish",
"first_value",
"following",
"generate",
"geomcollection",
"get_master_public_key",
"get_source_public_key",
"grouping",
"groups",
"gtid_only",
"histogram",
"history",
"inactive",
"initial",
"initiate",
"intersect",
"invisible",
"json_table",
"json_value",
"keyring",
"lag",
"last_value",
"lateral",
"lead",
"locked",
"master_compression_algorithms",
"master_public_key_path",
"master_tls_ciphersuites",
"master_zstd_compression_level",
"member",
"nested",
"network_namespace",
"nowait",
"nth_value",
"ntile",
"nulls",
"of",
"off",
"oj",
"old",
"optional",
"ordinality",
"organization",
"others",
"over",
"password_lock_time",
"path",
"percent_rank",
"persist",
"persist_only",
"preceding",
"privilege_checks_user",
"process",
"random",
"rank",
"recursive",
"reference",
"registration",
"replica",
"replicas",
"require_row_format",
"resource",
"respect",
"restart",
"retain",
"returning",
"reuse",
"role",
"row_number",
"secondary",
"secondary_engine",
"secondary_engine_attribute",
"secondary_load",
"secondary_unload",
"skip",
"source_auto_position",
"source_bind",
"source_compression_algorithms",
"source_connect_retry",
"source_delay",
"source_heartbeat_period",
"source_host",
"source_log_file",
"source_log_pos",
"source_password",
"source_port",
"source_public_key_path",
"source_retry_count",
"source_ssl",
"source_ssl_ca",
"source_ssl_capath",
"source_ssl_cert",
"source_ssl_cipher",
"source_ssl_crl",
"source_ssl_crlpath",
"source_ssl_key",
"source_ssl_verify_server_cert",
"source_tls_ciphersuites",
"source_tls_version",
"source_user",
"source_zstd_compression_level",
"srid",
"stream",
"system",
"thread_priority",
"ties",
"tls",
"unbounded",
"unregister",
"url",
"vcpu",
"visible",
"window",
"zone"}

constant_fields = {"id", "create_time", "update_time", "is_deleted"}

class DataDict(object):
    def __init__(self, host, port, user_name, password, db_name):
        # 数据库连接配置
        self.host_name = host
        self.port = port
        self.user_name = user_name
        self.password = password
        self.db_name = db_name
        self.folder_name = os.getcwd()

    def run(self):
        """脚本执行入口"""
        try:
            # 创建一个连接
            conn = pymysql.connect(host=self.host_name, port=self.port, user=self.user_name, 
            	password=self.password,database=self.db_name)
            # 用cursor()创建一个游标对象
            cursor = conn.cursor()
        except Exception:
            print('数据库连接失败，请检查连接信息！')
            exit(1)
    
        show_tables = 'show tables'
        cursor.execute(show_tables)
        rs = cursor.fetchall()
        for i in range(len(rs)):
            table_name = rs[i][0]
            tableNameChecker(table_name)
            tableNameKeyWordChecker(table_name)

            #print('开始生成表%s的数据字典' % (table_name,))
            table_sql = "show full columns from %s" % (table_name,)
            cursor.execute(table_sql)
            desc_rs = cursor.fetchall()

            column_set = []
            for j in range(len(desc_rs)):
                column_name = desc_rs[j][0]
                column_set.append(column_name)
                fieldNameChecker(table_name, column_name)
                fieldNameKeyWordChecker(table_name, column_name)
                column_type = desc_rs[j][1]

                fieldTypeChecker(table_name, column_name, column_type)
                column_null = desc_rs[j][3]
                column_defalut = desc_rs[j][5]
                if (column_defalut == None):
                    column_defalut = ''
                column_comments = desc_rs[j][8]
                if ((column_comments == None or column_comments == '')
                    and column_name not in constant_fields ):
                     print("表：" + table_name + " 属性名：" + column_name + " 没有注释")
            for field in constant_fields:
                if (field not in column_set):
                    print("表：" + table_name + " 不包含属性名：" + field)

        cursor.close()
        conn.close()


    def test_conn(self):
        """测试数据库连接"""
        try:
            # 创建一个连接
            pymysql.connect(host=self.host_name, port=self.port, user=self.user_name, 
            	password=self.password,database=self.db_name)
            return True
        except Exception as e:
            print(str(e))
            print("数据库连接失败")
            return False


def tableNameChecker(table_name):
    # 检查是否只包含小写字母、数字、_
    if not re.match(r'^[a-z0-9_]+$', table_name):
        print("表：" + table_name + "，不满足\"是否只包含小写字母、数字、_\"")
    # 检查是否以数字开头
    if table_name[0].isdigit():
        print("表：" + table_name + "，不满足\"是否以数字开头\"")

    # 检查是否以_开头
    if table_name[0] == '_':
        print("表：" + table_name + "，不满足\"检查是否以_开头\"")
    # 检查两个下划线中间是否只出现数字
    if re.search(r'_\d+_', table_name):
        print("表：" + table_name + "，不满足\"两个下划线中间是否只出现数字\"")

def tableNameKeyWordChecker(table_name):
    # 禁用保留字
    if (table_name in KEY_WORDS):
        print("表：" + table_name +  "，不满足\"禁用保留字\"")

def fieldNameChecker(table_name, column_name):
    # 检查是否只包含小写字母、数字、_
    if not re.match(r'^[a-z0-9_]+$', column_name):
        print("表：" + table_name + " 属性名：" + column_name + "，不满足\"是否只包含小写字母、数字、_\"")
    # 检查是否以数字开头
    if column_name[0].isdigit():
        print("表：" + table_name + " 属性名：" + column_name + "，不满足\"是否以数字开头\"")

    # 检查是否以_开头
    if column_name[0] == '_':
        print("表：" + table_name + " 属性名：" + column_name + "，不满足\"检查是否以_开头\"")
    # 检查两个下划线中间是否只出现数字
    if re.search(r'_\d+_', column_name):
        print("表：" + table_name + " 属性名：" + column_name + "，不满足\"两个下划线中间是否只出现数字\"")


def fieldNameKeyWordChecker(table_name, column_name):
    # 禁用保留字
    if (column_name in KEY_WORDS):
        print("表：" + table_name + " 属性名：" + column_name + "，不满足\"禁用保留字\"")

def fieldTypeChecker(table_name, column_name, column_type):
    # 小数类型为 decimal，禁止使用 float 和 double。
    if re.match(r'^float|double', column_type.lower() ):
        print("表：" + table_name + " 属性名：" + column_name + " 类型" + column_type + "，不满足\"小数类型为 decimal，禁止使用 float 和 double。\"")


if __name__ == '__main__':
    
    host='10.90.1.42'
    port=32436
    user='root'
    password='Tsingj_02!@'
    database='db_security'
   
    dataDict = DataDict(host, port, user, password, database)
    if dataDict.test_conn():
    	dataDict.run()
        