# kind: ConfigMap
# apiVersion: v1
# metadata:
#   namespace: {{ $.Release.Namespace }}
#   name: {{ $.Values.apollo.name }}-apollo-admin-server-configmap
# data:
#   application.properties: |
#     spring.datasource.url = jdbc:mysql://${MYSQL_ADDRESS}:3306/ApolloConfigDB?characterEncoding=utf8
#     spring.datasource.username = root
#     spring.datasource.password = FillInCorrectPassword
#     eureka.service.url = http://statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev:8080/eureka/,http://statefulset-apollo-config-server-dev-1.service-apollo-meta-server-dev:8080/eureka/