kind: Service
apiVersion: v1
metadata:
  name: {{ $.Values.apollo.name }}-apollo-mysql
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.apollo.name }}-apollo-mysql
spec:
  selector:
    app: {{ $.Values.apollo.name }}-apollo-mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort