apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.apollo.name }}-apollo-mysql-secret
  namespace: {{ $.Release.Namespace }}
## base64 
type: Opaque
data:
  mysql_user: root
  mysql_pwd: YUExMTExMTE=

