# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: gre-opengauss-pvc
#   namespace: gec-database
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 30Gi
#   storageClassName: yrcloudfile-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gec-gbase
  namespace: gec-database
  labels:
    name: gec-gbase
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gec-gbase
  template:
    metadata:
      labels: 
        name: gec-gbase
    spec:
      restartPolicy: Always
      containers:
      - name: gec-gbase
        image: shihd/gbase8a:1.0
        securityContext:
          privileged: true
        ports:
        - containerPort: 5258
          protocol: TCP
        resources:
          limits:
            cpu: 8
            memory: 10G
          requests:
            cpu: 1000m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gec-gbase-svc
  namespace: gec-database
  labels: 
    name: gec-gbase
spec:
  type: NodePort
  ports:
    - name: gbase-5258
      nodePort: 30102
      port: 5258
      protocol: TCP
      targetPort: 5258
  selector:
    name: gec-gbase