apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-namenode-pvc
  namespace: gec-database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: yrcloudfile-sc

---

apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: gec-database
  labels: 
    name: gec-hadoop-namenode
spec:
  type: NodePort
  ports:
    - name: haoop-namenode-50070
      port: 50070
      nodePort: 30080
      protocol: TCP
      targetPort: 50070
    - name: haoop-namenode-8020
      port: 8020
      protocol: TCP
      targetPort: 8020
  selector:
    name: gec-hadoop-namenode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gec-hadoop-namenode
  namespace: gec-database
  labels:
    name: gec-hadoop-namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gec-hadoop-namenode
  template:
    metadata:
      labels: 
        name: gec-hadoop-namenode
    spec:
      restartPolicy: Always
      containers:
      - name: gec-hadoop-namenode
        image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
        ports:
        - containerPort: 50070
          protocol: TCP
        env:
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
          value: "false"
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://namenode:8020"
        - name: CORE_CONF_hadoop_http_staticuser_user
          value: "root"
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          value: "*"
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          value: "*"
        - name: HDFS_CONF_dfs_webhdfs_enabled
          value: "true"
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        - name: YARN_CONF_yarn_log___aggregation___enable
          value: "true"
        - name: YARN_CONF_yarn_resourcemanager_recovery_enabled
          value: "true"
        - name: YARN_CONF_yarn_resourcemanager_store_class
          value: "org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore"
        - name: YARN_CONF_yarn_resourcemanager_fs_state___store_uri
          value: "/rmstate"
        - name: YARN_CONF_yarn_nodemanager_remote___app___log___dir
          value: "/app-logs"
        - name: YARN_CONF_yarn_log_server_url
          value: "http://historyserver:8188/applicationhistory/logs/"
        - name: YARN_CONF_yarn_timeline___service_enabled
          value: "true"
        - name: YARN_CONF_yarn_timeline___service_generic___application___history_enabled
          value: "true"
        - name: YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled
          value: "true"
        - name: YARN_CONF_yarn_resourcemanager_hostname
          value: "resourcemanager"
        - name: YARN_CONF_yarn_timeline___service_hostname
          value: "historyserver"
        - name: YARN_CONF_yarn_resourcemanager_address
          value: "resourcemanager:8032"
        - name: YARN_CONF_yarn_resourcemanager_scheduler_address
          value: "resourcemanager:8030"
        - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
          value: "resourcemanager:8031"
        - name: CLUSTER_NAME
          value: "test"
        resources:
          limits:
            cpu: 8
            memory: 8G
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /hadoop/dfs/name
          name: hadoop-namenode-pvc
      volumes:
      - name: hadoop-namenode-pvc
        persistentVolumeClaim:
          claimName: hadoop-namenode-pvc