kind: ConfigMap
apiVersion: v1
metadata:
  name: gec-hive-metastore-hive-site
  namespace: gec-database
  labels:
    name: gec-hive-metastore
data:
  hive-site.xml: |-
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property><name>hive.metastore.uris</name><value>thrift://hive-metastore:9083</value></property>
      <property><name>datanucleus.autoCreateSchema</name><value>false</value></property>
      <property><name>javax.jdo.option.ConnectionURL</name><value>jdbc:postgresql://hive-metastore-postgresql/metastore</value></property>
      <property><name>javax.jdo.option.ConnectionDriverName</name><value>org.postgresql.Driver</value></property>
      <property><name>javax.jdo.option.ConnectionPassword</name><value>hive</value></property>
      <property><name>javax.jdo.option.ConnectionUserName</name><value>hive</value></property>
    </configuration>



---

apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: gec-database
  labels: 
    name: hive-metastore
spec:
  type: NodePort
  ports:
    - name: hive-metastore-9083
      port: 9083
      nodePort: 30083
      protocol: TCP
      targetPort: 9083
  selector:
    name: gec-hive-metastore

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: gec-hive-metastore
  namespace: gec-database
  labels:
    name: gec-hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gec-hive-metastore
  template:
    metadata:
      labels: 
        name: gec-hive-metastore
    spec:
      restartPolicy: Always
      containers:
      - name: gec-hive-metastore
        image: bde2020/hive:2.3.2-postgresql-metastore
        ports:
        - containerPort: 9083
          protocol: TCP
        env:
        - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionURL
          value: "jdbc:postgresql://hive-metastore-postgresql/metastore"
        - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName
          value: "org.postgresql.Driver"
        - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName
          value: "hive"
        - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword
          value: "hive"
        - name: HIVE_SITE_CONF_datanucleus_autoCreateSchema
          value: "false"
        - name: HIVE_SITE_CONF_hive_metastore_uris
          value: "thrift://hive-metastore:9083"
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
          value: "false"
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://namenode:8020"
        - name: CORE_CONF_hadoop_http_staticuser_user
          value: "root"
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          value: "*"
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          value: "*"
        - name: HDFS_CONF_dfs_webhdfs_enabled
          value: "true"
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        - name: YARN_CONF_yarn_log___aggregation___enable
          value: "true"
        - name: YARN_CONF_yarn_resourcemanager_recovery_enabled
          value: "true"
        - name: YARN_CONF_yarn_resourcemanager_store_class
          value: "org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore"
        - name: YARN_CONF_yarn_resourcemanager_fs_state___store_uri
          value: "/rmstate"
        - name: YARN_CONF_yarn_nodemanager_remote___app___log___dir
          value: "/app-logs"
        - name: YARN_CONF_yarn_log_server_url
          value: "http://historyserver:8188/applicationhistory/logs/"
        - name: YARN_CONF_yarn_timeline___service_enabled
          value: "true"
        - name: YARN_CONF_yarn_timeline___service_generic___application___history_enabled
          value: "true"
        - name: YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled
          value: "true"
        - name: YARN_CONF_yarn_resourcemanager_hostname
          value: "resourcemanager"
        - name: YARN_CONF_yarn_timeline___service_hostname
          value: "historyserver"
        - name: YARN_CONF_yarn_resourcemanager_address
          value: "resourcemanager:8032"
        - name: YARN_CONF_yarn_resourcemanager_scheduler_address
          value: "resourcemanager:8030"
        - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
          value: "resourcemanager:8031"
        - name: SERVICE_PRECONDITION
          value: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
        command: ["/bin/bash", "/entrypoint.sh"]
        args: ["/opt/hive/bin/hive --service metastore"]
        resources:
          limits:
            cpu: 8
            memory: 8G
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: gec-hive-metastore-hive-site
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml 
      volumes:
      - name: gec-hive-metastore-hive-site
        configMap:
          name: gec-hive-metastore-hive-site