apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gec-hive-postgresql-pvc
  namespace: gec-database
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: yrcloudfile-sc
---

apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-postgresql
  namespace: gec-database
  labels: 
    name: gec-hive-metastore-postgresql
spec:
  type: NodePort
  ports:
    - name: hive-postgre-5432
      port: 5432
      nodePort: 30082
      protocol: TCP
      targetPort: 5432
  selector:
    name: gec-hive-metastore-postgresql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gec-hive-metastore-postgresql
  namespace: gec-database
  labels:
    name: gec-hive-metastore-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gec-hive-metastore-postgresql
  template:
    metadata:
      labels: 
        name: gec-hive-metastore-postgresql
    spec:
      restartPolicy: Always
      containers:
      - name: gec-hive-metastore-postgresql
        image: bde2020/hive-metastore-postgresql:2.3.0
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 8G
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: gec-hive-postgresql-pvc


